name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image:  cirrusci/flutter

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: flutter pub get
#    - name: Run tests
#      run: pub run test
    - name: Save Cache
      uses: actions/cache@v2
      with:
        path: ./
        key: build-${{ hashFiles('**/pubspec.lock') }}
        restore-key: pub-1

  test:
    runs-on: ubuntu-latest

    container:
      image:  cirrusci/flutter

    needs: build

    steps:
      - uses: actions/checkout@v2
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: ./
          key: build-${{ hashFiles('**/pubspec.lock') }}
          restore-key: pub-1

      - name: lint
        run: dartanalyzer lib





