name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image:  cirrusci/flutter

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: flutter pub get
#    - name: Run tests
#      run: pub run test
    - name: Cache
      uses: actions/cache@v2
      env:
        cache-name: cache-pub
      with:
        path: ~/.dart_tool
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-

  test:
    runs-on: ubuntu-latest

    container:
      image:  cirrusci/flutter

    steps:
      - name: Cache
      uses: actions/cache@v2
      env:
        cache-name: cache-pub
      with:
        path: ~/.dart_tool
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Test
        run: flutter docteur





