name: Dart CI

on:
  push:
  pull_request:
    branches:
      - "master"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@v1.5.0
        with:
          channel: master

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Checkout gallery code
        uses: actions/checkout@v2

      - name: Pub get
        run: flutter pub get

      - name: Analyse code
        run: dartanalyzer lib
        
  build-android:
    runs-on: ubuntu-latest
    needs: [ lint ]
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/master'
    steps:
      - name: Checkout gallery code
        uses: actions/checkout@v2

      - name: Install java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Clone Flutter repository
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.x'

      - name: Pub get
        run: flutter pub get

      - name: Decode secrets properties files
        run: touch .env; echo "AZURE_TRANSLATE_KEY=$AZURE_TRANSLATE_KEY" > .env; echo "$SECRETS_PROPERTIES" | base64 -d > ./android/key.properties;echo "$SECRETS_KEY" | base64 -d > ./android/upload-keystore.jks;echo "$GOOGLE_SERVICE" | base64 -d > ./android/app/google-services.json
        env:
          SECRETS_PROPERTIES: ${{ secrets.SECRETS_PROPERTIES }}
          SECRETS_KEY: ${{ secrets.SECRETS_KEY }}
          GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE }}

      - name: Build appBundle
        run: flutter build appbundle

      - name: Upload appBundle
        uses: actions/upload-artifact@v2
        with:
          name: appBundle
          path: build/app/outputs/bundle/release/app-release.aab

  build-ios:
    runs-on: macos-latest
    needs: [ lint ]
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/master'
    steps:
      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@v1.5.0
        with:
          channel: master

      - name: Checkout gallery code
        uses: actions/checkout@v2

      - name: Decode secrets properties files
        run: touch .env; echo "AZURE_TRANSLATE_KEY=$AZURE_TRANSLATE_KEY" > .env;echo "$IOS_GOOGLE_SERVICE" | base64 -d > ./ios/Runner/GoogleService-Info.plist
        env:
          AZURE_TRANSLATE_KEY: ${{ secrets.AZURE_TRANSLATE_KEY }}
          IOS_GOOGLE_SERVICE: ${{ secrets.IOS_GOOGLE_SERVICE }}

      - name: Pod install
        run: flutter clean && flutter pub get && cd ios/ && pod install

      - name: Build
        uses: sparkfabrik/ios-build-action@v1.1.0
        with:
          project-path: ./ios/Runner.xcodeproj
          p12-key-base64: ${{ secrets.P12_KEY_BASE64 }}
          p12-cer-base64: ${{ secrets.P12_CER_BASE64 }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.APPLE_TEAM_ID }}
          workspace-path: ./ios/Runner.xcworkspace






