name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.0'
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: flutter pub get
  #    - name: Run tests
  #      run: pub run test
      - name: Save Cache
        uses: actions/cache@v2
        with:
          path: ./
          key: build-${{ hashFiles('**/pubspec.lock') }}-1

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: ./
          key: build-${{ hashFiles('**/pubspec.lock') }}-1
#      - name: Install dependencies
#        run: flutter pub get
      - name: lint
        run: dartanalyzer lib





