name: Dart CI

on: push

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@v1.5.0
        with:
          channel: master

      - name: Checkout gallery code
        uses: actions/checkout@v2

      - name: Decode secrets properties files
        run: touch .env; echo "AZURE_TRANSLATE_KEY=$AZURE_TRANSLATE_KEY" > .env;echo "$IOS_GOOGLE_SERVICE" | base64 -d > ./ios/Runner/GoogleService-Info.plist
        env:
          AZURE_TRANSLATE_KEY: ${{ secrets.AZURE_TRANSLATE_KEY }}
          IOS_GOOGLE_SERVICE: ${{ secrets.IOS_GOOGLE_SERVICE }}

      - name: Pod install
        run: flutter clean && flutter pub get && cd ios/ && pod install

      - name: Build
        run: flutter build ios --release --no-codesign