name: Dart CI

on: push

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      # Set up Flutter.
      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@v1.5.0
        with:
          channel: master

      - name: Checkout gallery code
        uses: actions/checkout@v2

      - name: Decode secrets properties files
        run: touch .env; echo "AZURE_TRANSLATE_KEY=$AZURE_TRANSLATE_KEY" > .env;echo "$IOS_GOOGLE_SERVICE" | base64 -d > ./ios/Runner/GoogleService-Info.plist
        env:
          AZURE_TRANSLATE_KEY: ${{ secrets.AZURE_TRANSLATE_KEY }}
          IOS_GOOGLE_SERVICE: ${{ secrets.IOS_GOOGLE_SERVICE }}

      - name: Pod install
        run: flutter clean && flutter pub get && cd ios/ && pod install

      - name: Build
        uses: sparkfabrik/ios-build-action@v1.1.0
        with:
          project-path: ./ios/Runner.xcodeproj
          p12-key-base64: ${{ secrets.P12_KEY_BASE64 }}
          p12-cer-base64: ${{ secrets.P12_CER_BASE64 }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.APPLE_TEAM_ID }}
          workspace-path: ./ios/Runner.xcworkspace


